### ISSUE TITLE
Wrong screw for extruder part 11?

### ISSUE THREAD

**Issue by crundy** [Catastropheee/Skeleton3D#2]
We're currently putting together a Skeleton3D, but noticed that an M4x10 screw is not long enough to fit through the part "Mobile party.stl". I did take photos but managed to lose them in a phone disaster, but if you measure the space in the STL file above you can see it's 11.5mm, and a M4 20 would be too long and would press against the motor.

Screencap: http://crundyjunk.s3.amazonaws.com/MobilePartyLength.png

Could you double check and see if either we're doing something wrong or if indeed the screw part number is wrong?

P.S. The part numbers for the extruder page do not match between the full BoM and the English translation spreadsheet (e.g. 11 in the BoM is the M4x10 screw above, but in the English BoM 11 is an M3x40). Minor issues but thought you should know.

**Comment by Catastropheee** [comment]
Hi,

Thank you for your remark.
You're right, M4x10 is not the right screw for the "Mobile party". I use an
M4x16.

I will update the BOM soon!


2015-02-16 12:05 GMT+01:00 crundy <notifications@github.com>:

**Comment by crundy** [comment]
Thanks!
