### ISSUE TITLE
Unnecessary splitting of parts?

### ISSUE THREAD

**Issue by crundy** [Catastropheee/Skeleton3D#3]
Is there a particular reason why Plate_pusher.stl is separate from Z_support_plate_link.stl? lowering of the Z axis seems to by gravity only, as the plate pusher is not affixed to the Z support plate link, which generally wouldn't cause problems, but if a bearing got a stiff it could cause issues. Surely if you integrated the two parts so that the nut was fixed to the Z support plate link directly then you would have a more stable plate and less risk of the plate not lowering?

**Comment by Catastropheee** [comment]
It has been designed to uncouple guidance and traction which normally cause wobble.

" but if a bearing got a stiff it could cause issues" Which bearing ?

**Comment by crundy** [comment]
Fair enough. I haven't yet lined everything up properly so the Z axis is a little stiff, and so I was referring to the 4 bearings in the two Z support plates. Shouldn't be a problem once it's moving smoothly up and down. I'm guessing the weight of the wood and aluminium should suffice.
