### ISSUE TITLE
Fans

### ISSUE THREAD

**Issue by crundy** [Catastropheee/Skeleton3D#4]
Apologies, quick couple of questions about the extruder fans:
1. Re "Bec cooling.stl", this seems to be [sitting extremely close to the nozzle and hotend](http://crundyjunk.s3.amazonaws.com/Fan.PNG). Are you sure it won't melt?
2. Why are the vents for the above pointing directly at the bed? Would this rapid cooling not cause layers to peel up?
3. I note there is only one bolt holding each fan in one of the corners. Are you sure this is stable enough and won't cause the fans to wobble or slip? Fan 41 looks like it could untighten slightly and start rubbing against the X-shaft, and fan 42 looks like it could flop and smack into the Bec cooling part. I can look into some ways of adding another bolt for one of the holes or something to rest the edge on the side of the CoG unless you think it's isn't an issue?
4. Was there any reason to use two different fan sizes? Would two of the same be fine?

Thanks again for the design. We're almost there with ours.

**Comment by Catastropheee** [comment]
Hi,

1. It doesn't melt on my skeleton.

2. It's a good note. We need to improve this.

3. No problem with only one bolt. You can easily add a second bolt if you
want ;). Please share if you do it!

4. If we used a 40mm fan for the coldend we will loose 10mm print area!





2015-02-27 13:50 GMT+01:00 crundy <notifications@github.com>:

**Comment by crundy** [comment]
1 & 2: OK, I'm going to leave this part off for now. I presume it isn't essential.
3: Yes you are correct, I attached the 30mm fan and it holds in place fine, although it does point downwards very slightly. Shouldn't be a problem though.
4: Yup, my bad.
